version: '3.5'

services:
  all-ok-cron:
    build: .
    restart: always
    container_name: all-ok-cron
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - "${PWD}/crontab.conf.yml:/opt/crontab.conf.yml"
